### ISSUE TITLE
Capabilities "sensor"/"push notification"

### ISSUE THREAD

**Issue by frostieDE** [bilbob74/8Pass-WP8#1]
Why does the app need the capabilities `ID_CAP_PUSH_NOTIFICATION` or `ID_CAP_SENSORS`? See https://github.com/bilbob74/8Pass-WP8/blob/master/KeePass/Properties/WMAppManifest.xml

**Comment by bilbob74** [comment]
Maybe the App work with disabling both features. But there are some functions, where the app checks screen orientation. Maybe for this the sensor s are needed. On other places there are internal notifications. That's why I have learned the default option for push notifications on enabled.

You can try to disable both and report if this works. If so, I could delete both capabilities in the source code.

**Comment by frostieDE** [comment]
Well, for screen orientation there is no need for `ID_CAP_SENSORS`. It is all done by the framework. If you are using Toasts, you might be right when it comes to `ID_CAP_PUSH_NOTIFICATION` ;-)

**Comment by bilbob74** [comment]
The Toast comes from Coding4Fun Toolkit. Maybe i dont need ID_CAP_PUSH_NOTIFICATION in this Case. Its no real Push

**Comment by bilbob74** [comment]
I have removed both Capabilities, because they aren't necessary.
